extends: airbnb
plugins:
  - react
  - jsx-a11y
  # - import
rules:
  semi: ["error", "never"]
  no-plusplus: 0
  no-restricted-syntax: ["off", "ForInStatement"]
  max-len: 0
  newline-per-chained-call: 0
  no-undef: 1
  no-param-reassign: 0
  no-debugger: 0
  no-prototype-builtins: 0
  consistent-return: 0
