sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run cover
after_success:
  - npm run report-coverage
  - bash <(curl -s https://codecov.io/bash)
  # - npm run semantic-release
