sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run cover
after_success:
  - npm install -g codecov@2.x
  - codecov
  - npm run semantic-release
